### ISSUE TITLE
Missing argument names in JSON output for function pointer typedefs

### ISSUE THREAD

**Issue by webfolderio** [GMLC-TDC/cheader2json#84]
The JSON output for function pointer typedefs (like TraceLogCallback) is missing argument names.

Example header:
```C
#ifndef RLAPI
    #define RLAPI
#endif

#include <stdarg.h>

typedef void (*TraceLogCallback)(int logLevel, const char *text, va_list args);

RLAPI void SetTraceLogCallback(TraceLogCallback callback);
```

JSON output:
```json
{
    "kind": "TYPEDEF_DECL",
    "spelling": "TraceLogCallback",
    "type": "void (*)(int, const char *, va_list)",
    "start_line": 7,
    "end_line": 7
}
```

Expected: JSON should include argument names (logLevel, text, args).

**Comment by nightlark** [comment]
How would you want the argument names to be included? My initial take is something like this (though it wouldn't handle type names of a nested function pointer that gets taken as an argument):

```json
"arguments": [
    {
        "name": "logLevel",
        "type": "int"
    },
    {
        "name": "text",
        "type": "const char *"
    },
    {
        "name": "args",
        "type": "va_list"
    }
]
```

**Comment by nightlark** [comment]
I changed the name of the key to `function_pointer_arguments` and added a `function_pointer_result_type` field that has the return type. The presence of one of those keys can be used to check if the typedef is for a function pointer.

Testing with this monstrosity seems to work fine, so getting the names of arguments for nested function pointer arguments will work.
```cpp
typedef void (*TraceLogCallback)(int logLevel, const char *text, va_list args, void(*test)(int(*nestedmore)(int testint2)));
```

Technically the return type could itself be a function pointer, but I didn't handle that case (this is getting pretty convoluted):
```cpp
typedef int (*(*fptr)())();
```

**Comment by nightlark** [comment]
I uploaded a new tagged version to PyPI with this change -- you may need to force pip to install the updated version, since it is technically marked as a pre-release.
